# Generated by Django 3.2 on 2021-04-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('price', models.FloatField()),
            ],
            options={
                'db_table': 'laptop',
            },
        ),
    ]
